services:
  api:
    build:
      context: PI.ToDoMng.WebApi
      dockerfile: Dockerfile
    ports:
      - "8111:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080